# Import numpy

In [2]:
import numpy as np

# Creating Numpy Arrays

### 1. From Python Lists or Tuples

In [5]:
arr1 = np.array ([1,2,3])
print('1D array: \n',arr1)

arr2 = np.array([[1,2], [3,4]])
print('\n2D array: \n',arr2)

arr3 = np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print('\n3D array: \n', arr3)

1D array: 
 [1 2 3]

2D array: 
 [[1 2]
 [3 4]]

3D array: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


### 2. Using built-in functions

In [7]:
# 1. Create array with zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# 2. Create array with ones
one = np.ones((4,3))
print(one)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
# 3. Create array with a specific value
full_array = np.full((3,5),100)
print(full_array)

[[100 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [10]:
# 4. Identity matrix
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### 3. Using Ranges
np.arange(start, stop, step)

In [12]:
# 1. From 0 to specific number
np.arange(10) # Note that last number is excluded.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 2.From specific range
np.arange(10, 20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
# 3. Specific range with specific step
np.arange (1,30,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28])

In [15]:
# 4. np.linspace(start, stop, num)
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 4. Random Arrays

In [17]:
# 1. Uniform distribution between 0 and 1
np.random.rand(2,3)

array([[0.39809521, 0.81756332, 0.0150525 ],
       [0.17011657, 0.45655454, 0.03544688]])

In [18]:
# 2. Standard normal distribution
np.random.randn(2,3)

array([[ 0.66413066,  1.56644285, -0.62162768],
       [ 0.78587823, -1.43939017,  1.28483976]])

In [19]:
# 3. Random integer with a range
np.random.randint(1,10, size=(2,3))

array([[9, 7, 8],
       [2, 2, 3]])

### 5. From Existing Arrays

In [21]:
# 1. From existing arrays
original = np.array([1,2,3])
copy = np.copy(original)
copy

array([1, 2, 3])

In [22]:
# 2. Reshape
reshape_arr =np.arange(6).reshape((2,3))
reshape_arr

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
# 3. ravel()
reshape_arr.ravel()

array([0, 1, 2, 3, 4, 5])

# Essential NumPy Array Attributes

In [25]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [26]:
# 1. Number of dimensions
arr.ndim

2

In [27]:
# 2. Shape of the array
print(arr.shape)

(2, 3)


In [28]:
# 3. Total number of elements
print(arr.size)

6


In [29]:
# 4. Data type of elements
print(arr.dtype)

int32


In [30]:
# 5. Size of each item in bytes
print(arr.itemsize)

4


In [31]:
# 6. Total bytes consumed
print(arr.nbytes)

24


In [32]:
# 7. Transpose of the array
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [33]:
# Memory Address
arr.data

Summary Table of Attributes

| Attribute    | Description                        | Example Output       |
|--------------|------------------------------------|----------------------|
| `ndim`       | Number of dimensions               | `2`                  |
| `shape`      | Dimensions of array                | `(2, 3)`             |
| `size`       | Total number of elements           | `6`                  |
| `dtype`      | Type of each element               | `int64`              |
| `itemsize`   | Bytes per element                  | `8`                  |
| `nbytes`     | Total memory in bytes              | `48`                 |
| `T`          | Transpose of the array             | Swaps axes           |

# NumPy Array Operations

In [36]:
# 1. Arithmetic Operations ---> Element-wise
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print ('Sum: ',a+b)
print('Subtraction: ', a-b)
print('Multiplication: ', a*b)
print('Division: ', a/b)
print('Square: ', a ** 2)

Sum:  [5 7 9]
Subtraction:  [-3 -3 -3]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]
Square:  [1 4 9]


In [37]:
# 2. Aggregate Functions 
arr = np.array([[1,2,3], [4,5,6]])

print ('Sum of the elements: ',arr.sum())
print('Mean: ', arr.mean())
print ('Standard Deviation: ', arr.std())
print('Miminum Value: ', arr.min())
print ('Maximum Value: ', arr.max())
print ('Index of minimum value: ', arr.argmin())
print('Index of Maximum value: ', arr.argmax())

Sum of the elements:  21
Mean:  3.5
Standard Deviation:  1.707825127659933
Miminum Value:  1
Maximum Value:  6
Index of minimum value:  0
Index of Maximum value:  5


In [38]:
# Axis-wise operations:
print('Colume-wise sum: ',arr.sum(axis=0)) 
print('Row-wise sum: ',arr.sum(axis=1))

Colume-wise sum:  [5 7 9]
Row-wise sum:  [ 6 15]


In [40]:
# 3. Comparison & Boolean Operations

a = np.array([1,2,3])
b = np.array([2,2,2])
print('a is grater than b: ',a>b)
print ('a is less than or equal to b: ', a<= b)
print('a is equal to b: ',a==b)
print ('a is not equal to b :', a!=b)

a is grater than b:  [False False  True]
a is less than or equal to b:  [ True  True False]
a is equal to b:  [False  True False]
a is not equal to b : [ True False  True]


In [41]:
# Boolean masking
print(a[a>2])

[3]


In [42]:
# 4. Matrix Operations

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

In [43]:
# Matrix Multiplication
A.dot(B)

array([[19, 22],
       [43, 50]])

In [44]:
# Transpose:
A.T

array([[1, 3],
       [2, 4]])

In [45]:
# Inverese (Only works if A is square and invertible)
from numpy.linalg import inv
inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [46]:
# 5. Broadcasting
a = np.array([1,2,3])
b = 5
a+b

array([6, 7, 8])

In [47]:
a = np.array([[1],[2],[3]])
b = np.array([4,5,6])
a+b

array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

In [48]:
# 6. Stacking
x = np.array([[1,2]])
y = np.array([[3,4]])

In [49]:
# Vertical Stack
np.vstack([x,y])

array([[1, 2],
       [3, 4]])

In [50]:
# Horizontal Stack
np.hstack([x,y])

array([[1, 2, 3, 4]])

In [51]:
# 7. Useful Utilities
arr = [1 ,2, 4, 4, 6, 2, 1, 1, 2, 6]
np.unique(a)

array([1, 2, 3])

In [52]:
unique_values, index = np.unique(arr, return_index=True)
print(index)

[0 1 2 4]


In [53]:
unique_vals, counts = np.unique(arr, return_counts=True)
print(unique_vals)
print(counts)

[1 2 4 6]
[3 3 2 2]


In [54]:
np.sort(a)

array([[1],
       [2],
       [3]])