# NumPy Array Functions

In [2]:
# Mathematical Functions
import numpy as np

arr = np.array([0, np.pi/2, np.pi])
arr

array([0.        , 1.57079633, 3.14159265])

In [3]:
print(np.sin(arr))   # [0.0, 1.0, 0.0]
print(np.cos(arr))   # [1.0, 0.0, -1.0]
print(np.exp(arr))   # Exponential
print(np.log(arr + 1))  # Natural log (added 1 to avoid log(0))
print(np.sqrt(arr))  # Square root

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 1.          4.81047738 23.14069263]
[0.         0.94421571 1.42108041]
[0.         1.25331414 1.77245385]


In [4]:
# Round function

a = np.array([1.2345, 2.3456])

print(np.round(a, 2))    # [1.23 2.35]
print(np.floor(a))       # [1. 2.]
print(np.ceil(a))        # [2. 3.]

[1.23 2.35]
[1. 2.]
[2. 3.]


In [5]:
# Statistical Functions

arr = np.array([[1, 2], [3, 4]])

print(np.mean(arr))      # Mean
print(np.median(arr))    # Median
print(np.std(arr))       # Standard deviation
print(np.var(arr))       # Variance
print(np.percentile(arr, 50))  # 50th percentile
print(np.percentile(arr, 90))  # 90th percentile

2.5
2.5
1.118033988749895
1.25
2.5
3.7


In [6]:
# Logical & conditional functions

arr = np.array([1, 2, 3, 4])

print(np.any(arr > 2))     
print(np.all(arr > 0))     
print(np.where(arr > 2, 'Yes', 'No')) 


True
True
['No' 'No' 'Yes' 'Yes']


In [7]:
# Set functions

a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

print(np.union1d(a, b))         
print(np.intersect1d(a, b))     
print(np.setdiff1d(a, b))      
print(np.setxor1d(a, b))

[1 2 3 4 5 6]
[3 4]
[1 2]
[1 2 5 6]


In [8]:
# Clipping & Cumulative
arr = np.array([1, 2, 3, 4, 5])

print(np.clip(arr, 2, 4))  # Limit values to [2, 4]
print(np.cumsum(arr))      # Cumulative sum
print(np.cumprod(arr))     # Cumulative product

[2 2 3 4 4]
[ 1  3  6 10 15]
[  1   2   6  24 120]


# Splitting Arrays in NumPy
Splitting means dividing an array into multiple sub-arrays.

Functions for Splitting
| Function         | Description                                |
|------------------|--------------------------------------------|
| `np.split()`     | Split equally along an axis                |
| `np.array_split()` | Split **unequally** along an axis        |
| `np.hsplit()`    | Split **horizontally** (column-wise)       |
| `np.vsplit()`    | Split **vertically** (row-wise)            |
| `np.dsplit()`    | Split along **depth** (for 3D arrays)      |

In [10]:
# 1. np.split(): Equal Split
arr = np.array([1,2,3,4, 5,6,7,8])
print(arr)

print(np.split(arr,4))

[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [11]:
# 2. Unequal Split Allowed ----> np.array_split()

np.array_split(arr, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7]), array([8])]

In [12]:
# 3. Horizontal Split (Columns) ----> np.hsplit()
arr2d = np.array([[1,2,3,4],
                  [5,6,7,8]])

np.hsplit(arr2d, 2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [13]:
# 4. Vertical Split (Rows) ----> np.vsplit()

np.vsplit(arr2d, 2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

In [14]:
# 5. Depth Split (3D arrays) ----> np.dsplit()

arr3D = np.arange(8).reshape(2, 2, 2)
print(np.dsplit(arr3D, 2))

[array([[[0],
        [2]],

       [[4],
        [6]]]), array([[[1],
        [3]],

       [[5],
        [7]]])]


In [15]:
arr3D

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

# NumPy Joining Array
Joining means combining multiple arrays into a single array.
| Function        | Description                   | Adds Axis? |
| --------------- | ----------------------------- | ---------- |
| `concatenate()` | Join along existing axis      | ❌ No       |
| `stack()`       | Join along new axis           | ✅ Yes      |
| `hstack()`      | Join along columns            | ❌ No       |
| `vstack()`      | Join along rows               | ❌ No       |
| `dstack()`      | Join along third axis (depth) | ✅ Yes      |

In [17]:
# 1. np.concatenate() ---->1D
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [18]:
# Concatenate ----> 2D
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7,8]])

np.concatenate((a, b), axis=0)
# Vertical join: shape becomes (3, 2)


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
# 2. np.stack()

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.stack((a, b), axis=0))
print('-'* 15)
print(np.stack((a, b), axis=1))

# Transformed to higher dimentions.

[[1 2 3]
 [4 5 6]]
---------------
[[1 4]
 [2 5]
 [3 6]]


In [20]:
# 3. Horizontal Stack ------> np.hstack()

np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [21]:
# 2D
a = np.array([[1], [2]])
b = np.array([[3], [4]])

np.hstack((a, b))

array([[1, 3],
       [2, 4]])

In [22]:
# 4. Vertical Stack ----> np.vstack()

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
# 5. Depth Stack (for 3D arrays) -----> np.dstack()

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.dstack((a, b))

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# NumPy Array Indexing
Indexing means accessing elements of a NumPy array using indices or conditions.
| Type             | Syntax Example           | Purpose                       |
| ---------------- | ------------------------ | ----------------------------- |
| Basic Indexing   | `arr[2]`                 | Access element at index       |
| Slicing          | `arr[1:4]`               | Get a range of values         |
| Boolean Indexing | `arr[arr > 10]`          | Filter based on condition     |
| Fancy Indexing   | `arr[[0, 2, 4]]`         | Access elements by index list |
| 2D Indexing      | `arr[1, 2]`, `arr[1][2]` | Access specific rows/cols     |
| `np.where()`     | `np.where(arr > 10)`     | Conditional selection         |

In [25]:
# 1. Basic Indexing (1D Arrays)

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])     # 1st element
print(arr[-1])    # last element

10
50


In [26]:
# 2. Indexing in 2D Arrays

arr2d = np.array([[1, 2, 3],
                  [4, 5, 6]])

print(arr2d[0, 1])   # Row 0, col 1
print(arr2d[1, 2])   # Row 1, col 2

2
6


In [27]:
arr2d[1][2]

6

In [28]:
# 3. Slicing

arr = np.array([0, 10, 20, 30, 40, 50])
print(arr[1:4]) # Index no.4 will be excluded.
print(arr[:3]) 
print(arr[::2])

[10 20 30]
[ 0 10 20]
[ 0 20 40]


In [29]:
# 2D Slicing

arr2d = np.array([[10, 20, 30],
                  [40, 50, 60],
                  [70, 80, 90]])

arr2d[0:2, 1:]

array([[20, 30],
       [50, 60]])

In [30]:
# 4. Boolean Indexing (Filtering)

arr = np.array([5, 10, 15, 20, 25])
mask = arr > 15

print(mask)
print(arr[arr > 15])

[False False False  True  True]
[20 25]


In [31]:
# 5. Fancy Indexing (List of Indices)

arr = np.array([100, 200, 300, 400, 500])
idx = [0, 2, 3]
arr[idx]

array([100, 300, 400])

In [32]:
# Direct
arr[[0,2,3]]

array([100, 300, 400])

In [33]:
# 6. Advanced ---- Modify Multiple Elements

arr = np.array([10, 20, 30, 40])
arr[[0, 2]] = [-1, -2]
print(arr)  # [-1 20 -2 40]

[-1 20 -2 40]


In [34]:
# Use np.where()
arr = np.array([10, 20, 30, 40])

print(np.where(arr > 25))        # Index Number
print(arr[np.where(arr>25)])     # Values

(array([2, 3], dtype=int64),)
[30 40]


In [35]:
# Multi-Condition Filtering

arr = np.array([10, 20, 30, 40, 50])
arr[(arr > 20) & (arr < 50)]


array([30, 40])

# NumPy Array Slicing
Slicing allows us to extract parts of an array using index ranges.  
It uses the syntax: array[start:stop:step]

| Expression            | Description                    |
| --------------------- | ------------------------------ |
| `arr[start:stop]`     | Slice from `start` to `stop-1` |
| `arr[:n]`             | First `n` elements             |
| `arr[-n:]`            | Last `n` elements              |
| `arr[::step]`         | Step through array             |
| `arr[::-1]`           | Reverse array                  |
| `arr2d[r1:r2, c1:c2]` | 2D slice by rows and columns   |

In [37]:
# 1. 1D Array Slicing – Basics

import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])
print(arr[:3])
print(arr[::2])
print(arr[::-1])   #(Reversed)

[20 30 40]
[10 20 30]
[10 30 50]
[60 50 40 30 20 10]


In [38]:
# 2. 2D Array Slicing
arr2d = np.array([[11, 12, 13],
                  [21, 22, 23],
                  [31, 32, 33]])

print(arr2d[0:2, 1:3]) 

[[12 13]
 [22 23]]


In [39]:
# 3. Slice With Step (Striding)

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr[1:7:2]

array([1, 3, 5])

In [40]:
arr2d = np.arange(16).reshape(4, 4)
print(arr2d,'\n')
# Take every second row and every second column
arr2d[::2, ::2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 



array([[ 0,  2],
       [ 8, 10]])

In [41]:
# 4. Modify Arrays Using Slicing

arr = np.array([10, 20, 30, 40, 50])
arr[1:4] = 99
arr

array([10, 99, 99, 99, 50])

In [42]:
# 5. Slicing with Negative Indices

arr = np.array([100, 200, 300, 400, 500])
print(arr[-3:])
print(arr[-4:-1])

[300 400 500]
[200 300 400]


In [43]:
# 6. Advanced 2D Slicing Patterns
arr2d = np.array([[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12],
                  [13, 14, 15, 16]])

# Center 2x2 block
arr2d[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [44]:
# Extract border
arr2d[:, [0, -1]]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12],
       [13, 16]])

# NumPy Array Iterating

In [46]:
# 1. Iterating 1D Arrays (Basic)
arr = np.array([10, 20, 30])

for x in arr:
    print(x)

10
20
30


In [47]:
# 2. Iterating 2D Arrays
arr2d = np.array([[1, 2], [3, 4]])

for row in arr2d:
    print("Row:", row)
    for val in row:
        print("Value:", val)

Row: [1 2]
Value: 1
Value: 2
Row: [3 4]
Value: 3
Value: 4


In [48]:
for row in arr2d:
    for val in row:
        print(val)

1
2
3
4


In [49]:
# 3. Iterating 3D Arrays
arr3d = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

for block in arr3d:
    for row in block:
        for val in row:
            print(val)

1
2
3
4
5
6
7
8


In [50]:
# 4. Efficient Element-wise Iteration
# np.nditer() lets iterate over every element, regardless of dimensions.

arr = np.array([[1, 2], [3, 4]])

for x in np.nditer(arr):
    print(x)

1
2
3
4


In [51]:
# Add write access:
arr = np.array([[1, 2], [3, 4]])

for x in np.nditer(arr, op_flags=['readwrite']):
    x[...] = x * 10  # Modify in-place

print(arr)  # [[10 20]
            #  [30 40]]

[[10 20]
 [30 40]]


In [52]:
# 5. Iterating With Data Type Control

arr = np.array([[1, 2], [3, 4]])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'


In [53]:
# 6. Using np.ndenumerate() – Get Index + Value
arr = np.array([[10, 20], [30, 40]])

for index, val in np.ndenumerate(arr):
    print("Index:", index, "Value:", val)


Index: (0, 0) Value: 10
Index: (0, 1) Value: 20
Index: (1, 0) Value: 30
Index: (1, 1) Value: 40
